name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Submodules
        run: |
          echo "Updating Submodules"
          git submodule update --remote --merge

      - name: Check for Changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Add Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          echo "Adding Changes"
          git add .

      - name: Commit Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          echo "Committing Changes"
          git commit -m "Update submodules" || exit 0

      - name: Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          echo "Pushing Changes"
          git push origin main
